### ISSUE TITLE
Funktionsanforderung 2: Übersicht aller Einträge für das Backoffice

### ISSUE THREAD

**Issue by Seppi00** [jku-win-se/teaching-2023.ws.prse.braeuer.team4#3]
### User Story:
Als Mitarbeiter des Backoffice wünsche ich mir eine zentrale Übersicht aller erfassten Fahrteneinträge, um sicherzustellen, dass sämtliche Fahrten ordnungsgemäß protokolliert wurden.

### Anforderungen an die Funktion:
- Eine klare und vollständige Anzeige aller Fahrteneinträge im System.

### Kriterien an die Funktion:
- Das Backoffice sollte Zugriff auf eine verständliche Übersicht aller Fahrteneinträge haben.

**Comment by MeinGitAccount** [comment]
Obsolet: Abgedeckt durch den Punkt "Die Informationen sollten gespeichert und angezeigt werden können." des Issue 1
