### ISSUE TITLE
Update Readme und Link zum Prototypen

### ISSUE THREAD

**Issue by johannes-b** [jku-win-se/teaching-2023.ws.prse.braeuer.team4#9]
## Update Readme und Link zum Prototypen

- [x] Den Inhalt der aktuellen ./README.md in die Datei verschieben ./docs/automation.md verschieben
- [x] Die leere ./README.md des Projekts wie folgt ergänzen:

---
# Praktikum Software Engineering WS2023 - “Digital Driver’s Logbook”
*Eine kurze (2-3 Sätze) Beschreibung des Projekts* 

## Prototype
*Link zum Prototype* 

## Installation
*Wie kann man die Applikation ausführen?*

---

**Comment by johannes-b** [comment]
Hallo @MeinGitAccount, @Seppi00, und @SoJakob , 

dieses Ticket bitte im nächsten Sprint umsetzen.

**Comment by SoJakob** [comment]
Tasks done. README updated
